name: ci1stlab testing
description: testing for ci 1st lab yml file
on: push

jobs:
  ci:
    runs-on: ubuntu-latest
    steps: 
      - name: download code
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven

    
    
